platform :osx, '10.12'

target_name = 'RSSReader'

use_frameworks!
project target_name

target target_name do
  pod 'AFNetworking', '~> 3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

